# Generated by Django 4.2.7 on 2026-01-08 06:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_taskrequestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrequestlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
