# Generated by Django 4.2.7 on 2025-12-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es_integration', '0002_add_configs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_field', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
