# Generated by Django 4.2.7 on 2025-12-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('es_integration', '0003_dashboardstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardStats',
        ),
    ]
