# Generated by Django 4.2.7 on 2025-12-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es_integration', '0004_delete_dashboardstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_alerts', models.IntegerField()),
                ('critical_alerts', models.IntegerField(blank=True, null=True)),
                ('high_alerts', models.IntegerField(blank=True, null=True)),
                ('medium_alerts', models.IntegerField(blank=True, null=True)),
                ('low_alerts', models.IntegerField(blank=True, null=True)),
                ('raw_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_seconds', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
