# Generated by Django 4.2.7 on 2026-01-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('es_integration', '0005_dashboardstats_schedulerconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'managed': False},
        ),
    ]
